server:
  port: 8086

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: wom-estudiante-service
          uri: lb://wom-estudiante-service
          predicates:
            - Path=/estudiantes/**
        - id: wom-curso-service
          uri: lb://wom-curso-service
          predicates:
            - Path=/cursos/**
        - id: wom-matricula-service
          uri: lb://wom-matricula-service
          predicates:
            - Path=/matriculas/**
        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
              - Path=/auth/**
